from argparse import ArgumentParser
arg = ArgumentParser()
arg.add_argument("--experiment-name", type=str, required=True)
arg.add_argument("--model", type=str, required=True)
arg.add_argument("--tokenizer", type=str, required=True)
arg.add_argument("--dataset", type=str, required=True)
arg.add_argument("--num-epochs", type=int, default=1)
arg.add_argument("--lr", type=float, default=8e-5)
arg.add_argument("--loss-fn", type=str, default="min_harmful_loss")
arg.add_argument("--local-model", type=str, default="")
arg.add_argument("--test-batch-size", type=int, default=4)
arg.add_argument("--train-batch-size", type=int, default=4)
arg.add_argument("--adversarial-alpha", type=float, default=0.1)  # 0.1 for Llama2
arg.add_argument("--random-init", type=str, default="")
arg.add_argument("--steps-to-eval", type=int, default=50)
arg.add_argument("--train-harmful-subset", type=str, default="all")
arg.add_argument("--test-harmful-subset", type=str, default="all")
arg.add_argument("--withhold-harmful-subset", type=str, default="")
arg.add_argument("--strong-attack", type=str, default="")
arg.add_argument("--use-refusal", type=str, default="true")
arg.add_argument("--on-vector", type=str, default="true")
arg.add_argument("--attack-steps", type=int, default=10000)
arg.add_argument("--defence-steps", type=int, default=10000)
arg.add_argument("--ntl-alpha", type=float, default=1)
arg.add_argument("--ntl-beta", type=float, default=0.001)
arg.add_argument("--ntl-num-layers", type=int, default=6)
arg.add_argument("--warmup-factor", type=float, default=0.1)
arg.add_argument("--scheduler", type=str, default="cosine")
arg.add_argument("--kernel-mul", type=float, default=2.0)
arg.add_argument("--kernel-num", type=int, default=5)
arg.add_argument("--regularization-term", type=float, default=0.1)
arg.add_argument("--num-cycles", type=int, default=1)
arg.add_argument("--save", type=str, default="false")
arg.add_argument("--construct-mask", type=str, default="")
arg.add_argument("--mask-path", type=str, default="")
arg.add_argument("--optimizer", type=str, default="adam")
arg.add_argument("--sample", type=str, default="")
arg.add_argument("--seed", type=int, default=42)
arg.add_argument("--freeze", type=str, default=None)
arg.add_argument("--initial-left-pad", type=str, default="")
arg.add_argument("--remove-question", type=str, default="")
arg.add_argument("--disjoint_attack", type=bool, default=False)
arg.add_argument("--disjoint_attack_test", type=bool, default=False)

# vaccine 
arg.add_argument("--vaccine-rho", type=float, default=1)

ARGS = arg.parse_args()